# Creating build pipeline for dotnet app
stages:
  - stage: Continuosintegration
    displayName: Continuosintegration
    jobs:
    - job: dotnetbuild
      displayName: dotnetbuildjob
      steps:
      - script: dotnet restore
        displayName: restore
      - script: dotnet build
        displayName: build
      - script: dotnet test
        displayName: test
      - script: dotnet publish
        displayName: publish artifact